spring:
  # 기본 프로파일을 local로 설정 (2.4 버전 이전 설정으로 일단은 설정 // 어차피 embedded 자체가 테스트용)
  # 자세한 내용 : https://multifrontgarden.tistory.com/277
  config:
    use-legacy-processing: true

  profiles:
    active: local

  datasource:
    url: jdbc:mariadb://localhost:3306/websocket
    driver-class-name: org.mariadb.jdbc.Driver
    username: root
    password: 1234

  jpa:
    hibernate:
      ddl-auto: create # 애플리케이션 실행시점에 테이블 다 지우고 새로 생성
    properties:
      hibernate:
        # show_sql: true
        format_sql: true
        default_batch_fetch_size: 1000 #1대다 쿼리 뻥튀기 페이징 문제, 최적화 옵션 (MAX는 거의 1000)

  # static파일을 개발할때 서버를 재시작 하지 않고도 수정한 내용이 반영되도록
  devtools:
    livereload:
      enabled: true
    restart:
      enabled: false
  freemarker:
    cache: false

logging.level:
  org.hibernate.SQL: debug # hibernate가 생상하는 로그를 다 보여줌
# org.hibernate.type: trace # 쿼리 파라미터 로그 남기기