# Generated by Django 3.2.7 on 2021-09-03 01:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Quesion',
            new_name='Question',
        ),
    ]
